from __future__ import annotations
from enum import Enum


class ConversationStateKind(str, Enum):
    NEW = "NEW"
    OUTBOUND_SENT = "OUTBOUND_SENT"
    ENGAGED = "ENGAGED"
    QUALIFYING = "QUALIFYING"
    QUESTIONED = "QUESTIONED"
    ACTION_READY = "ACTION_READY"
    ACTION_CONFIRMED = "ACTION_CONFIRMED"
    WAITING = "WAITING"
    NOT_INTERESTED = "NOT_INTERESTED"
    STOPPED = "STOPPED"
    AUTO_REPLY = "AUTO_REPLY"
    CUSTOMER_RECALL = "CUSTOMER_RECALL"
    CUSTOMER_APPOINTMENT = "CUSTOMER_APPOINTMENT"
    ENDED = "ENDED"
